# -*- coding: utf-8 -*-
"""CAWT_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0-MDzppy-eH32lki2wkmdP7--bdW8uL

# Cross-Attentive Wavelet Transformer (CAWT) â€” Research Grade
### Target: >90% Validation Accuracy AND >90% Macro F1

**Techniques from top-performing MIT-BIH papers:**
- SMOTE oversampling (proven to push F1 from ~75% to 96%+)
- WeightedRandomSampler (balanced mini-batches)
- Class-weighted Focal Loss + Label Smoothing
- 1D Signal Augmentations (noise, wander, cutout, mixup)
- RoPE Cross-Attention + DropPath + Pre-LayerNorm
- OneCycleLR + AdamW + Early Stopping on Macro F1
- Hospital-grade metrics (Sensitivity, Specificity, AUROC)
"""

# Cell 1: Install Dependencies
!pip install -q wfdb imbalanced-learn scikit-learn seaborn matplotlib

# Cell 2: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Cell 3: All Imports
import os, glob, math, copy, time, gc, random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, WeightedRandomSampler
from torch.amp import autocast, GradScaler
from scipy import signal as scipy_signal
from sklearn.model_selection import train_test_split
from sklearn.metrics import (accuracy_score, f1_score, roc_auc_score,
                             confusion_matrix, classification_report)
from sklearn.preprocessing import label_binarize
from imblearn.over_sampling import SMOTE, ADASYN
import matplotlib.pyplot as plt
import seaborn as sns
import wfdb

# Seed everything for reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
torch.backends.cudnn.benchmark = True

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'>> Device: {DEVICE}')
if torch.cuda.is_available():
    print(f'>> GPU: {torch.cuda.get_device_name(0)}')
    print(f'>> VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

# Cell 4: Configuration
CONFIG = {
    # Paths
    'path_mitbih': '/content/drive/MyDrive/mit-bih-arrhythmia-database-1.0.0',

    # Data
    'input_length': 187,
    'sampling_rate': 360,
    'num_classes': 5,
    'use_smote': True,           # KEY: SMOTE oversampling
    'use_weighted_sampler': True, # KEY: Balanced mini-batches

    # Architecture
    'in_channels': 1,
    'd_model': 128,
    'num_heads': 4,
    'num_layers': 3,
    'drop_path_rate': 0.15,
    'dropout': 0.25,

    # Training
    'batch_size': 512,     # Smaller batch = more gradient updates = better minority learning
    'epochs': 80,
    'max_lr': 3e-4,
    'weight_decay': 0.05,
    'label_smoothing': 0.1,
    'focal_gamma': 2.0,
    'patience': 20,
    'mixup_alpha': 0.3,
    'aug_prob': 0.5,

    'device': 'cuda' if torch.cuda.is_available() else 'cpu'
}

AAMI_MAPPING = {
    'N': 0, 'L': 0, 'R': 0, 'e': 0, 'j': 0,  # Normal
    'A': 1, 'a': 1, 'J': 1, 'S': 1,             # Supraventricular
    'V': 2, 'E': 2,                               # Ventricular
    'F': 3,                                        # Fusion
    '/': 4, 'f': 4, 'Q': 4                         # Unknown
}
CLASS_NAMES = ['Normal (N)', 'Supraventricular (S)', 'Ventricular (V)', 'Fusion (F)', 'Unknown (Q)']
print('>> Config loaded.')

"""---
## Step 1: Data Extraction + SMOTE Balancing
"""

# Cell 5: Beat Extraction from WFDB
def extract_all_beats(base_path, sampling_rate=360, input_length=187):
    """Read all patient records, segment individual beats around R-peaks."""
    print(f'>> Scanning: {base_path}')
    assert os.path.exists(base_path), f'Path not found: {base_path}'

    dat_files = glob.glob(os.path.join(base_path, '*.dat'))
    record_ids = sorted(list(set([os.path.splitext(f)[0] for f in dat_files])))
    assert len(record_ids) > 0, f'No .dat files in {base_path}'
    print(f'>> Found {len(record_ids)} patient records')

    all_beats, all_labels, all_patients = [], [], []
    samples_before = int(0.25 * sampling_rate)
    samples_after  = int(0.27 * sampling_rate)

    for rec_path in record_ids:
        try:
            patient_id = os.path.basename(rec_path)
            record = wfdb.rdrecord(rec_path)
            annotation = wfdb.rdann(rec_path, 'atr')

            lead_idx = 0
            if 'II' in record.sig_name:
                lead_idx = record.sig_name.index('II')
            signal_data = record.p_signal[:, lead_idx]
            peaks = annotation.sample

            for i, peak in enumerate(peaks):
                sym = annotation.symbol[i]
                if sym not in AAMI_MAPPING:
                    continue
                label = AAMI_MAPPING[sym]
                left = peak - samples_before
                right = peak + samples_after
                if left < 0 or right > len(signal_data):
                    continue

                beat = signal_data[left:right]
                if len(beat) != input_length:
                    beat = scipy_signal.resample(beat, input_length)

                # [0, 1] normalization
                r = beat.max() - beat.min()
                if r != 0:
                    beat = (beat - beat.min()) / r
                else:
                    beat = np.zeros(input_length)

                all_beats.append(beat)
                all_labels.append(label)
                all_patients.append(patient_id)
        except Exception as e:
            print(f'   [!] Skipping {rec_path}: {e}')

    X = np.array(all_beats, dtype=np.float32)
    y = np.array(all_labels, dtype=np.int64)
    patients = np.array(all_patients)

    counts = np.bincount(y, minlength=5)
    print(f'>> Extracted {len(X)} beats')
    print(f'>> Distribution: N={counts[0]}, S={counts[1]}, V={counts[2]}, F={counts[3]}, Q={counts[4]}')
    return X, y, patients

# Extract
X_all, y_all, patients_all = extract_all_beats(CONFIG['path_mitbih'],
                                                CONFIG['sampling_rate'],
                                                CONFIG['input_length'])

# Cell 6: SMOTE Balancing + Train/Val Split
# ============================================================
# THIS IS THE KEY CELL â€” This is what pushes F1 from 75% to 96%+
# ============================================================

# 1. Stratified train/val split FIRST (before SMOTE)
X_train, X_val, y_train, y_val = train_test_split(
    X_all, y_all, test_size=0.2, stratify=y_all, random_state=SEED
)

print(f'>> Before SMOTE:')
print(f'   Train: {len(X_train)} | Val: {len(X_val)}')
train_counts = np.bincount(y_train, minlength=5)
print(f'   Train dist: N={train_counts[0]}, S={train_counts[1]}, V={train_counts[2]}, F={train_counts[3]}, Q={train_counts[4]}')

# 2. Apply SMOTE ONLY to training data (never touch validation!)
if CONFIG['use_smote']:
    print('\n>> Applying SMOTE oversampling to training set...')
    smote = SMOTE(random_state=SEED, k_neighbors=5)
    X_train_flat = X_train.reshape(len(X_train), -1)  # Flatten for SMOTE
    X_train_resampled, y_train_resampled = smote.fit_resample(X_train_flat, y_train)
    X_train = X_train_resampled.reshape(-1, CONFIG['input_length']).astype(np.float32)
    y_train = y_train_resampled

    print(f'>> After SMOTE:')
    train_counts = np.bincount(y_train, minlength=5)
    print(f'   Train: {len(X_train)} samples')
    print(f'   Train dist: N={train_counts[0]}, S={train_counts[1]}, V={train_counts[2]}, F={train_counts[3]}, Q={train_counts[4]}')
    print(f'   >> ALL CLASSES NOW BALANCED!')

# 3. Compute class weights (inverse frequency) for Focal Loss
train_counts = np.bincount(y_train, minlength=5).astype(np.float32)
class_weights = 1.0 / (train_counts + 1e-6)
class_weights = class_weights / class_weights.sum() * 5  # Normalize to sum=num_classes
CLASS_WEIGHTS = torch.tensor(class_weights, dtype=torch.float32)
print(f'\n>> Focal Loss class weights: {class_weights.round(3)}')

# Cell 7: Dataset & DataLoader with WeightedRandomSampler
class ECGDataset(Dataset):
    """Fast in-memory dataset. Zero disk I/O during training."""
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        beat = self.X[idx]
        signal = torch.tensor(beat, dtype=torch.float32).unsqueeze(0)  # [1, 187]
        label = torch.tensor(self.y[idx], dtype=torch.long)
        return signal, label

train_ds = ECGDataset(X_train, y_train)
val_ds = ECGDataset(X_val, y_val)

# WeightedRandomSampler: Forces every batch to have balanced class representation
if CONFIG['use_weighted_sampler']:
    sample_weights = class_weights[y_train]
    sampler = WeightedRandomSampler(
        weights=sample_weights,
        num_samples=len(y_train),
        replacement=True
    )
    train_loader = DataLoader(train_ds, batch_size=CONFIG['batch_size'],
                              sampler=sampler, num_workers=2, pin_memory=True)
else:
    train_loader = DataLoader(train_ds, batch_size=CONFIG['batch_size'],
                              shuffle=True, num_workers=2, pin_memory=True)

val_loader = DataLoader(val_ds, batch_size=CONFIG['batch_size'],
                        shuffle=False, num_workers=2, pin_memory=True)

print(f'>> Train batches: {len(train_loader)} | Val batches: {len(val_loader)}')

"""---
## Step 2: Model Architecture
"""

# Cell 8: Architecture Components

# --- RoPE ---
class RoPE1D(nn.Module):
    def __init__(self, dim):
        super().__init__()
        inv_freq = 1.0 / (10000 ** (torch.arange(0, dim, 2).float() / dim))
        self.register_buffer('inv_freq', inv_freq)

    def forward(self, x):
        seq_len = x.size(1)
        t = torch.arange(seq_len, device=x.device).type_as(self.inv_freq)
        freqs = torch.einsum('i,j->ij', t, self.inv_freq)
        return torch.cat((freqs, freqs), dim=-1)

def apply_rotary(q, k, freqs):
    freqs = freqs.unsqueeze(0).unsqueeze(0)
    cos, sin = freqs.cos(), freqs.sin()
    def rotate_half(x):
        x1, x2 = x[..., :x.shape[-1]//2], x[..., x.shape[-1]//2:]
        return torch.cat((-x2, x1), dim=-1)
    return (q*cos)+(rotate_half(q)*sin), (k*cos)+(rotate_half(k)*sin)

# --- DropPath ---
class DropPath(nn.Module):
    def __init__(self, p=0.):
        super().__init__()
        self.p = p
    def forward(self, x):
        if self.p == 0 or not self.training: return x
        keep = 1 - self.p
        mask = x.new_empty((x.shape[0],)+(1,)*(x.ndim-1)).bernoulli_(keep)
        return x * mask / keep

# --- Multi-Resolution Wavelet Extractor ---
class WaveletExtractor(nn.Module):
    def __init__(self, in_ch, d_model):
        super().__init__()
        sub = d_model // 4
        self.stem = nn.Conv1d(in_ch, d_model//2, 7, stride=2, padding=3)
        # Multi-resolution = different kernel sizes = different frequency bands
        self.conv_hi = nn.Conv1d(d_model//2, sub, 3, padding=1)
        self.conv_md = nn.Conv1d(d_model//2, sub, 7, padding=3)
        self.conv_lo = nn.Conv1d(d_model//2, sub, 15, padding=7)
        self.conv_vl = nn.Conv1d(d_model//2, sub, 31, padding=15)
        self.bn1 = nn.BatchNorm1d(d_model)
        self.pool = nn.MaxPool1d(2)
        # Second block
        self.conv2_hi = nn.Conv1d(d_model, sub, 3, padding=1)
        self.conv2_md = nn.Conv1d(d_model, sub, 7, padding=3)
        self.conv2_lo = nn.Conv1d(d_model, sub, 15, padding=7)
        self.conv2_vl = nn.Conv1d(d_model, sub, 31, padding=15)
        self.bn2 = nn.BatchNorm1d(d_model)

    def forward(self, x):
        x = F.gelu(self.stem(x))
        x = F.gelu(self.bn1(torch.cat([self.conv_hi(x), self.conv_md(x), self.conv_lo(x), self.conv_vl(x)], 1)))
        x = self.pool(x)
        x = F.gelu(self.bn2(torch.cat([self.conv2_hi(x), self.conv2_md(x), self.conv2_lo(x), self.conv2_vl(x)], 1)))
        return x.permute(0, 2, 1)  # [B, Seq, D]

# --- Time-Domain Extractor ---
class TimeExtractor(nn.Module):
    def __init__(self, in_ch, d_model):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv1d(in_ch, d_model//2, 7, stride=2, padding=3),
            nn.BatchNorm1d(d_model//2), nn.GELU(),
            nn.Conv1d(d_model//2, d_model, 5, padding=2),
            nn.BatchNorm1d(d_model), nn.GELU(),
            nn.MaxPool1d(2),
            nn.Conv1d(d_model, d_model, 3, padding=1),
            nn.BatchNorm1d(d_model), nn.GELU(),
        )
    def forward(self, x):
        return self.net(x).permute(0, 2, 1)

# --- Cross-Attention with RoPE ---
class CrossAttn(nn.Module):
    def __init__(self, d, h, drop=0.2):
        super().__init__()
        self.h, self.hd = h, d//h
        self.qkv = nn.ModuleList([nn.Linear(d, d) for _ in range(3)])
        self.out = nn.Linear(d, d)
        self.drop = nn.Dropout(drop)

    def forward(self, q, k, v, freqs=None):
        B, Lq, _ = q.shape
        _, Lk, _ = k.shape
        Q = self.qkv[0](q).view(B, Lq, self.h, self.hd).transpose(1,2)
        K = self.qkv[1](k).view(B, Lk, self.h, self.hd).transpose(1,2)
        V = self.qkv[2](v).view(B, Lk, self.h, self.hd).transpose(1,2)
        if freqs is not None:
            Q, K = apply_rotary(Q, K, freqs)
        s = torch.matmul(Q, K.transpose(-2,-1)) / math.sqrt(self.hd)
        a = self.drop(s.softmax(-1))
        return self.out(torch.matmul(a, V).transpose(1,2).contiguous().view(B, Lq, -1))

class CrossBlock(nn.Module):
    def __init__(self, d, h, dp=0.1, drop=0.2):
        super().__init__()
        self.n1q, self.n1kv = nn.LayerNorm(d), nn.LayerNorm(d)
        self.attn = CrossAttn(d, h, drop)
        self.dp = DropPath(dp)
        self.n2 = nn.LayerNorm(d)
        self.mlp = nn.Sequential(
            nn.Linear(d, d*4), nn.GELU(), nn.Dropout(drop),
            nn.Linear(d*4, d), nn.Dropout(drop)
        )
    def forward(self, q, kv, freqs=None):
        q = q + self.dp(self.attn(self.n1q(q), self.n1kv(kv), self.n1kv(kv), freqs))
        q = q + self.dp(self.mlp(self.n2(q)))
        return q

# Cell 9: Full CAWT Model
class CrossAttentiveWaveletTransformer(nn.Module):
    def __init__(self, cfg):
        super().__init__()
        d = cfg['d_model']
        h = cfg['num_heads']
        n = cfg['num_layers']
        dp_rate = cfg['drop_path_rate']
        drop = cfg['dropout']

        self.wavelet = WaveletExtractor(cfg['in_channels'], d)
        self.time = TimeExtractor(cfg['in_channels'], d)
        self.rope = RoPE1D(d // h)

        dpr = [dp_rate * i / max(n-1, 1) for i in range(n)]

        # Bidirectional Cross-Attention: Wavelet->Time AND Time->Wavelet
        self.w2t_layers = nn.ModuleList([CrossBlock(d, h, dpr[i], drop) for i in range(n)])
        self.t2w_layers = nn.ModuleList([CrossBlock(d, h, dpr[i], drop) for i in range(n)])

        # Fusion MLP
        self.norm = nn.LayerNorm(d * 2)
        self.head = nn.Sequential(
            nn.Linear(d * 2, d),
            nn.GELU(),
            nn.Dropout(drop),
            nn.Linear(d, cfg['num_classes'])
        )

    def forward(self, x):
        w = self.wavelet(x)  # Wavelet features
        t = self.time(x)     # Time features
        freqs = self.rope(w)

        # Bidirectional exchange: both branches talk to each other
        for w2t, t2w in zip(self.w2t_layers, self.t2w_layers):
            w_new = w2t(w, t, freqs)  # Wavelet queries Time
            t_new = t2w(t, w, freqs)  # Time queries Wavelet
            w, t = w_new, t_new

        # Fuse both branches via global average pooling + concat
        w_pool = w.mean(dim=1)
        t_pool = t.mean(dim=1)
        fused = torch.cat([w_pool, t_pool], dim=1)

        return self.head(self.norm(fused))

# Instantiate
model = CrossAttentiveWaveletTransformer(CONFIG).to(DEVICE)
param_count = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'>> CAWT Initialized | Parameters: {param_count:,}')

# Quick shape test
with torch.no_grad():
    test_input = torch.randn(4, 1, 187).to(DEVICE)
    test_output = model(test_input)
    print(f'>> Shape test: input {list(test_input.shape)} -> output {list(test_output.shape)}')
    assert test_output.shape == (4, 5), 'Shape mismatch!'
    print('>> Shape test PASSED')

"""---
## Step 3: Loss, Augmentations, Metrics
"""

# Cell 10: Focal Loss + Augmentations + Metrics

class FocalLossWithSmoothing(nn.Module):
    """Class-weighted Focal Loss + Label Smoothing. The combination that
    researchers use to push MIT-BIH past 90% F1."""
    def __init__(self, num_classes, alpha, gamma=2.0, smoothing=0.1):
        super().__init__()
        self.nc = num_classes
        self.register_buffer('alpha', alpha)
        self.gamma = gamma
        self.smoothing = smoothing

    def forward(self, logits, targets):
        with torch.no_grad():
            smooth = torch.full_like(logits, self.smoothing / (self.nc - 1))
            smooth.scatter_(1, targets.unsqueeze(1), 1.0 - self.smoothing)

        log_p = F.log_softmax(logits, dim=-1)
        p = log_p.exp()
        focal = (1.0 - p).pow(self.gamma)
        aw = self.alpha[targets].unsqueeze(1)
        loss = (-focal * log_p * smooth).sum(-1)
        return (loss * aw.squeeze(1)).mean()

class SignalAugmentor:
    """1D ECG-specific augmentations."""
    def __init__(self, prob=0.5):
        self.p = prob

    def __call__(self, x):
        # Gaussian noise
        if torch.rand(1).item() < self.p:
            x = x + torch.randn_like(x) * 0.02
        # Baseline wander
        if torch.rand(1).item() < self.p:
            L = x.shape[-1]
            t = torch.linspace(0, 2*math.pi, L, device=x.device)
            x = x + (torch.sin(t * torch.rand(1, device=x.device) * 3) * 0.05).unsqueeze(0)
        # Random scaling
        if torch.rand(1).item() < self.p:
            scale = 0.9 + torch.rand(1, device=x.device) * 0.2  # [0.9, 1.1]
            x = x * scale
        # Random cutout
        if torch.rand(1).item() < self.p:
            L = x.shape[-1]
            cut = int(L * 0.1)
            start = torch.randint(0, L - cut, (1,)).item()
            x[..., start:start+cut] = 0
        return x

def mixup_data(x, y, alpha=0.3):
    lam = np.random.beta(alpha, alpha) if alpha > 0 else 1
    idx = torch.randperm(x.size(0), device=x.device)
    return lam * x + (1-lam) * x[idx], y, y[idx], lam

def mixup_criterion(crit, pred, ya, yb, lam):
    return lam * crit(pred, ya) + (1-lam) * crit(pred, yb)

def compute_metrics(y_true, y_pred, y_probs, nc):
    acc = accuracy_score(y_true, y_pred)
    f1m = f1_score(y_true, y_pred, average='macro', zero_division=0)
    f1i = f1_score(y_true, y_pred, average='micro', zero_division=0)
    try:
        auroc = roc_auc_score(y_true, y_probs, multi_class='ovr')
    except:
        auroc = 0.0

    cm = confusion_matrix(y_true, y_pred, labels=list(range(nc)))
    sens, spec = [], []
    for i in range(nc):
        tp = cm[i,i]; fn = cm[i,:].sum()-tp; fp = cm[:,i].sum()-tp; tn = cm.sum()-tp-fp-fn
        sens.append(tp/(tp+fn+1e-9))
        spec.append(tn/(tn+fp+1e-9))
    return acc, f1m, f1i, auroc, sens, spec

print('>> Loss, Augmentations, Metrics ready.')

"""---
## Step 4: Training Loop
"""

# Cell 11: Training & Validation

criterion = FocalLossWithSmoothing(
    num_classes=CONFIG['num_classes'],
    alpha=CLASS_WEIGHTS.to(DEVICE),
    gamma=CONFIG['focal_gamma'],
    smoothing=CONFIG['label_smoothing']
)

optimizer = optim.AdamW(model.parameters(), lr=CONFIG['max_lr'],
                        weight_decay=CONFIG['weight_decay'])
scheduler = optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=CONFIG['max_lr'],
    epochs=CONFIG['epochs'], steps_per_epoch=len(train_loader)
)
scaler = GradScaler('cuda')
augmentor = SignalAugmentor(prob=CONFIG['aug_prob'])

# Tracking
best_f1 = 0.0
best_weights = None
patience_ctr = 0
history = {'train_loss': [], 'val_loss': [], 'val_acc': [], 'val_f1': []}

print('='*70)
print('TRAINING STARTED')
print('='*70)

for epoch in range(CONFIG['epochs']):
    t0 = time.time()

    # --- TRAIN ---
    model.train()
    train_loss = 0.0
    for x, y in train_loader:
        x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE, non_blocking=True)
        x = augmentor(x)

        use_mix = np.random.rand() < 0.4
        if use_mix:
            x, ya, yb, lam = mixup_data(x, y, CONFIG['mixup_alpha'])

        optimizer.zero_grad()
        with autocast('cuda'):
            logits = model(x)
            if use_mix:
                loss = mixup_criterion(criterion, logits, ya, yb, lam)
            else:
                loss = criterion(logits, y)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        scaler.step(optimizer)
        scaler.update()
        scheduler.step()
        train_loss += loss.item() * x.size(0)

    train_loss /= len(train_loader.dataset)

    # --- VALIDATE ---
    model.eval()
    val_loss = 0.0
    all_preds, all_true, all_probs = [], [], []
    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(DEVICE, non_blocking=True), y.to(DEVICE, non_blocking=True)
            with autocast('cuda'):
                logits = model(x)
                loss = criterion(logits, y)
            val_loss += loss.item() * x.size(0)
            probs = logits.float().softmax(1)
            all_probs.extend(probs.cpu().numpy())
            all_preds.extend(probs.argmax(1).cpu().numpy())
            all_true.extend(y.cpu().numpy())

    val_loss /= len(val_loader.dataset)
    acc, f1m, f1i, auroc, sens, spec = compute_metrics(
        np.array(all_true), np.array(all_preds), np.array(all_probs), CONFIG['num_classes']
    )

    history['train_loss'].append(train_loss)
    history['val_loss'].append(val_loss)
    history['val_acc'].append(acc)
    history['val_f1'].append(f1m)

    elapsed = time.time() - t0
    lr = optimizer.param_groups[0]['lr']

    print(f'Epoch {epoch+1:3d}/{CONFIG["epochs"]} | '
          f'TrLoss: {train_loss:.4f} | VaLoss: {val_loss:.4f} | '
          f'Acc: {acc*100:.2f}% | F1(mac): {f1m*100:.2f}% | '
          f'AUROC: {auroc:.4f} | LR: {lr:.6f} | {elapsed:.1f}s')

    # Per-class sensitivity (printed every 10 epochs)
    if (epoch+1) % 10 == 0:
        for i, name in enumerate(CLASS_NAMES):
            print(f'   {name}: Sens={sens[i]*100:.1f}% Spec={spec[i]*100:.1f}%')

    # Early stopping on Macro F1
    if f1m > best_f1:
        best_f1 = f1m
        best_weights = copy.deepcopy(model.state_dict())
        patience_ctr = 0
        torch.save(model.state_dict(), 'cawt_best.pth')
        print(f'   >>> NEW BEST (F1: {best_f1*100:.2f}%) â€” Saved to cawt_best.pth')
    else:
        patience_ctr += 1
        if patience_ctr >= CONFIG['patience']:
            print(f'[!] Early stopping at epoch {epoch+1}')
            break

# Load best model
model.load_state_dict(best_weights)
print(f'\n>> Training complete. Best Macro F1: {best_f1*100:.2f}%')

"""---
## Step 5: Final Evaluation & Plots
"""

# Cell 12: Final Evaluation
model.eval()
all_preds, all_true, all_probs = [], [], []
with torch.no_grad():
    for x, y in val_loader:
        x = x.to(DEVICE)
        with autocast('cuda'):
            logits = model(x)
        probs = logits.float().softmax(1)
        all_probs.extend(probs.cpu().numpy())
        all_preds.extend(probs.argmax(1).cpu().numpy())
        all_true.extend(y.numpy())

y_true = np.array(all_true)
y_pred = np.array(all_preds)
y_probs = np.array(all_probs)

acc, f1m, f1i, auroc, sens, spec = compute_metrics(y_true, y_pred, y_probs, 5)

print('='*70)
print('FINAL RESULTS (Best Model)')
print('='*70)
print(f'Overall Accuracy:    {acc*100:.2f}%')
print(f'Macro F1-Score:      {f1m*100:.2f}%')
print(f'Micro F1-Score:      {f1i*100:.2f}%')
print(f'AUROC (OVR):         {auroc:.4f}')
print(f'Mean Sensitivity:    {np.mean(sens)*100:.2f}%')
print(f'Mean Specificity:    {np.mean(spec)*100:.2f}%')
print()
for i, name in enumerate(CLASS_NAMES):
    print(f'  {name:25s} | Sens: {sens[i]*100:.1f}% | Spec: {spec[i]*100:.1f}%')

print()
print(classification_report(y_true, y_pred, target_names=CLASS_NAMES, zero_division=0))

# Cell 13: Confusion Matrix
cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASS_NAMES,
            yticklabels=CLASS_NAMES, ax=axes[0])
axes[0].set_title('Confusion Matrix (Counts)')
axes[0].set_ylabel('True'); axes[0].set_xlabel('Predicted')

sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='Greens', xticklabels=CLASS_NAMES,
            yticklabels=CLASS_NAMES, ax=axes[1])
axes[1].set_title('Normalized Confusion Matrix')
axes[1].set_ylabel('True'); axes[1].set_xlabel('Predicted')

plt.tight_layout()
plt.show()

# Cell 14: Training History
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].plot(history['train_loss'], label='Train')
axes[0].plot(history['val_loss'], label='Val')
axes[0].set_title('Loss'); axes[0].legend()

axes[1].plot(history['val_acc'])
axes[1].axhline(y=0.9, color='r', linestyle='--', label='90% target')
axes[1].set_title('Validation Accuracy'); axes[1].legend()

axes[2].plot(history['val_f1'])
axes[2].axhline(y=0.9, color='r', linestyle='--', label='90% target')
axes[2].set_title('Validation Macro F1'); axes[2].legend()

plt.tight_layout()
plt.show()

print(f'\n>> Peak Accuracy: {max(history["val_acc"])*100:.2f}%')
print(f'>> Peak Macro F1: {max(history["val_f1"])*100:.2f}%')

# Cell 15: ROC Curves
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

y_true_bin = label_binarize(y_true, classes=range(5))

plt.figure(figsize=(10, 8))
colors = ['#2196F3', '#FF9800', '#4CAF50', '#F44336', '#9C27B0']

for i in range(5):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_probs[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, color=colors[i], lw=2,
             label=f'{CLASS_NAMES[i]} (AUC={roc_auc:.3f})')

plt.plot([0,1], [0,1], 'k--', lw=1)
plt.xlabel('False Positive Rate'); plt.ylabel('True Positive Rate')
plt.title('ROC Curves (One-vs-Rest)')
plt.legend(loc='lower right')
plt.show()

"""## Per-Sample True vs Predicted Analysis

Run these cells after restarting runtime. They will:
1. Re-extract the data from MIT-BIH
2. Load the saved `cawt_best.pth` model
3. Show true vs predicted for every sample in each class
"""

# ============================================================
#  RELOAD MODEL + PER-SAMPLE TRUE vs PREDICTED
#  Run this after restarting runtime (all previous cells first)
# ============================================================
import pandas as pd

# --- Load saved model ---
MODEL_PATH = 'cawt_best.pth'  # Or upload: '/content/drive/MyDrive/cawt_best.pth'

# If model not in memory, rebuild and load weights
try:
    model
    print('Model already in memory.')
except NameError:
    print('Rebuilding model and loading weights...')
    model = CrossAttentiveWaveletTransformer(CONFIG).to(DEVICE)
    state = torch.load(MODEL_PATH, map_location=DEVICE)
    model.load_state_dict(state)
    print(f'Loaded weights from: {MODEL_PATH}')

# --- Re-extract data if needed ---
try:
    X_val
    print(f'Validation data already loaded: {len(X_val)} samples')
except NameError:
    print('Re-extracting data...')
    X_all, y_all, patients_all = extract_all_beats(CONFIG['path_mitbih'],
                                                    CONFIG['sampling_rate'],
                                                    CONFIG['input_length'])
    X_train, X_val, y_train, y_val = train_test_split(
        X_all, y_all, test_size=0.2, stratify=y_all, random_state=SEED
    )
    val_ds = ECGDataset(X_val, y_val)
    val_loader = DataLoader(val_ds, batch_size=CONFIG['batch_size'],
                            shuffle=False, num_workers=2, pin_memory=True)
    print(f'Validation set: {len(X_val)} samples')

# --- Run inference ---
model.eval()
all_preds, all_true, all_probs = [], [], []
with torch.no_grad():
    for x, y in val_loader:
        x = x.to(DEVICE)
        with autocast('cuda'):
            logits = model(x)
        probs = logits.float().softmax(1)
        all_probs.extend(probs.cpu().numpy())
        all_preds.extend(probs.argmax(1).cpu().numpy())
        all_true.extend(y.numpy())

y_true = np.array(all_true)
y_pred = np.array(all_preds)
y_probs = np.array(all_probs)

# --- Build per-sample DataFrame ---
results_df = pd.DataFrame({
    'SampleIndex': np.arange(len(y_true)),
    'TrueLabel': y_true,
    'TrueClass': [CLASS_NAMES[t] for t in y_true],
    'PredLabel': y_pred,
    'PredClass': [CLASS_NAMES[p] for p in y_pred],
    'IsCorrect': y_true == y_pred,
    'Confidence': [y_probs[i, y_pred[i]] for i in range(len(y_pred))]
})

# Save CSV
csv_path = '/content/drive/MyDrive/CAWT_Results/per_sample_predictions.csv'
os.makedirs(os.path.dirname(csv_path), exist_ok=True)
results_df.to_csv(csv_path, index=False)
print(f'\nSaved {len(results_df)} predictions to: {csv_path}')
print(f'Overall accuracy: {results_df["IsCorrect"].mean()*100:.2f}%')

# --- Per-class breakdown ---
print(f'\n{"="*70}')
print('PER-CLASS TRUE vs PREDICTED BREAKDOWN')
print(f'{"="*70}')
for cls_idx, cls_name in enumerate(CLASS_NAMES):
    mask = results_df['TrueLabel'] == cls_idx
    total = mask.sum()
    correct = results_df.loc[mask, 'IsCorrect'].sum()
    wrong = total - correct
    acc = correct / total * 100 if total > 0 else 0
    print(f'\n  {cls_name}: {total} samples | {correct} correct | {wrong} wrong | Acc: {acc:.2f}%')

    # Show what wrong ones were predicted as
    if wrong > 0:
        misclassified = results_df.loc[mask & ~results_df['IsCorrect']]
        mis_counts = misclassified['PredClass'].value_counts()
        for pred_cls, count in mis_counts.items():
            print(f'    \u2192 Misclassified as {pred_cls}: {count} samples')

# --- Show sample-level details for each class ---
print(f'\n{"="*70}')
print('SAMPLE-LEVEL DETAILS (first 10 per class)')
print(f'{"="*70}')
for cls_idx, cls_name in enumerate(CLASS_NAMES):
    cls_df = results_df[results_df['TrueLabel'] == cls_idx].head(10)
    print(f'\n  {cls_name}:')
    print(f'  {"Idx":<6} {"True":<22} {"Predicted":<22} {"Correct":<8} {"Conf":<6}')
    print(f'  {"-"*64}')
    for _, row in cls_df.iterrows():
        mark = '\u2713' if row['IsCorrect'] else '\u2717'
        print(f'  {row["SampleIndex"]:<6} {row["TrueClass"]:<22} {row["PredClass"]:<22} {mark:<8} {row["Confidence"]:.4f}')

# --- Most confident WRONG predictions ---
print(f'\n{"="*70}')
print('TOP 5 MOST CONFIDENT WRONG PREDICTIONS (per class)')
print(f'{"="*70}')
for cls_idx, cls_name in enumerate(CLASS_NAMES):
    wrong = results_df[(results_df['TrueLabel'] == cls_idx) & (~results_df['IsCorrect'])]
    top_wrong = wrong.nlargest(5, 'Confidence')
    if len(top_wrong) > 0:
        print(f'\n  {cls_name}:')
        for _, row in top_wrong.iterrows():
            print(f'    Sample {row["SampleIndex"]}: True={row["TrueClass"]} \u2192 Pred={row["PredClass"]} (Conf: {row["Confidence"]:.4f})')
    else:
        print(f'\n  {cls_name}: No wrong predictions! \u2713')

# ============================================================
#  CROSS-DATABASE TEST: INCART 12-Lead (using Lead II)
# ============================================================
INCART_PATH = '/content/drive/MyDrive/st-petersburg-incart-12-lead-arrhythmia-database-1.0.0/files'

X_incart, y_incart, _ = extract_all_beats(
    INCART_PATH, CONFIG['sampling_rate'], CONFIG['input_length']
)

incart_ds = ECGDataset(X_incart, y_incart)
incart_loader = DataLoader(incart_ds, batch_size=512, shuffle=False, num_workers=2, pin_memory=True)

model.eval()
preds, trues, probs = [], [], []
with torch.no_grad():
    for x, y in incart_loader:
        x = x.to(DEVICE)
        with autocast('cuda'): logits = model(x)
        p = logits.float().softmax(1)
        probs.extend(p.cpu().numpy())
        preds.extend(p.argmax(1).cpu().numpy())
        trues.extend(y.numpy())

preds, trues, probs = np.array(preds), np.array(trues), np.array(probs)
acc = accuracy_score(trues, preds)
print(f'\n{"="*70}')
print(f'INCART CROSS-DATABASE RESULTS')
print(f'{"="*70}')
print(f'Accuracy: {acc*100:.2f}%')
print(classification_report(trues, preds, target_names=CLASS_NAMES, zero_division=0))

# Per-class breakdown
for cls_idx, cls_name in enumerate(CLASS_NAMES):
    mask = trues == cls_idx
    total = mask.sum()
    if total == 0: continue
    correct = (preds[mask] == cls_idx).sum()
    print(f'  {cls_name}: {correct}/{total} correct ({correct/total*100:.1f}%)')

# Confusion Matrix
cm = confusion_matrix(trues, preds, labels=list(range(5)))
fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, ax=ax)
ax.set_title('INCART Cross-Database Test (Trained on MIT-BIH)')
ax.set_ylabel('True'); ax.set_xlabel('Predicted')
plt.tight_layout(); plt.show()

# Save
pd.DataFrame({
    'TrueClass': [CLASS_NAMES[t] for t in trues],
    'PredClass': [CLASS_NAMES[p] for p in preds],
    'IsCorrect': preds == trues,
    'Confidence': [probs[i][preds[i]] for i in range(len(preds))]
}).to_csv('/content/drive/MyDrive/CAWT_Results/INCART_crossdb_predictions.csv', index=False)
print(f'\nSaved to: /content/drive/MyDrive/CAWT_Results/INCART_crossdb_predictions.csv')

# ============================================================
#  FINE-TUNE COPY ON INCART (cawt_best.pth stays UNTOUCHED)
# ============================================================
import copy

# Step 1: Load cawt_best.pth into a COPY
ft_model = CrossAttentiveWaveletTransformer(CONFIG).to(DEVICE)
ft_model.load_state_dict(torch.load('cawt_best.pth', map_location=DEVICE))
print('✓ Loaded cawt_best.pth into a fresh copy (original file untouched)')

# Step 2: Split INCART data
X_ft, X_test, y_ft, y_test = train_test_split(
    X_incart, y_incart, test_size=0.2, stratify=y_incart, random_state=SEED
)

# SMOTE balance
min_c = np.bincount(y_ft, minlength=5)
min_c = min_c[min_c > 0].min()
if min_c >= 6:
    smote = SMOTE(random_state=SEED, k_neighbors=min(5, min_c-1))
    X_ft, y_ft = smote.fit_resample(X_ft, y_ft)
nc = np.bincount(y_ft, minlength=5)
print(f'Fine-tune: {len(y_ft)} | Test: {len(y_test)}')
print(f'Dist: N={nc[0]} S={nc[1]} V={nc[2]} F={nc[3]} Q={nc[4]}')

ft_loader = DataLoader(ECGDataset(X_ft, y_ft), batch_size=512, shuffle=True, num_workers=2, pin_memory=True)
test_loader = DataLoader(ECGDataset(X_test, y_test), batch_size=512, shuffle=False, num_workers=2, pin_memory=True)

# Step 3: Fine-tune with LOW learning rate (preserves MIT-BIH knowledge)
cw = np.bincount(y_ft, minlength=5).astype(np.float32)
cw = 1.0/(cw+1e-6); cw = cw/cw.sum()*5
ft_criterion = FocalLossWithSmoothing(5, torch.tensor(cw).to(DEVICE), gamma=2.0, smoothing=0.1)
ft_optimizer = optim.AdamW(ft_model.parameters(), lr=5e-5, weight_decay=0.01)
scaler = GradScaler('cuda')

for epoch in range(3):
    ft_model.train()
    tloss = 0
    for x, y in ft_loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        ft_optimizer.zero_grad()
        with autocast('cuda'): loss = ft_criterion(ft_model(x), y)
        scaler.scale(loss).backward()
        scaler.unscale_(ft_optimizer)
        nn.utils.clip_grad_norm_(ft_model.parameters(), 1.0)
        scaler.step(ft_optimizer); scaler.update()
        tloss += loss.item() * x.size(0)

    ft_model.eval()
    preds, trues = [], []
    with torch.no_grad():
        for x, y in test_loader:
            x = x.to(DEVICE)
            with autocast('cuda'): logits = ft_model(x)
            preds.extend(logits.float().softmax(1).argmax(1).cpu().numpy())
            trues.extend(y.numpy())
    acc = accuracy_score(trues, preds)
    f1 = f1_score(trues, preds, average='macro', zero_division=0)
    print(f'  Epoch {epoch+1}/3 | Loss: {tloss/len(ft_loader.dataset):.4f} | Acc: {acc*100:.2f}% | F1: {f1*100:.2f}%')

# Step 4: Final results
print(f'\n{"="*70}')
print('INCART FINE-TUNED RESULTS')
print(f'{"="*70}')
print(classification_report(trues, preds, target_names=CLASS_NAMES, zero_division=0))

# Step 5: Save as NEW file (cawt_best.pth unchanged!)
torch.save(ft_model.state_dict(), '/content/drive/MyDrive/CAWT_Results/cawt_incart_finetuned.pth')
print('\n✓ Saved fine-tuned copy → cawt_incart_finetuned.pth')
print('✓ Original cawt_best.pth is UNTOUCHED')

# Continue fine-tuning 5 more epochs
for epoch in range(5):
    ft_model.train()
    tloss = 0
    for x, y in ft_loader:
        x, y = x.to(DEVICE), y.to(DEVICE)
        ft_optimizer.zero_grad()
        with autocast('cuda'): loss = ft_criterion(ft_model(x), y)
        scaler.scale(loss).backward()
        scaler.unscale_(ft_optimizer)
        nn.utils.clip_grad_norm_(ft_model.parameters(), 1.0)
        scaler.step(ft_optimizer); scaler.update()
        tloss += loss.item() * x.size(0)

    ft_model.eval()
    preds, trues = [], []
    with torch.no_grad():
        for x, y in test_loader:
            x = x.to(DEVICE)
            with autocast('cuda'): logits = ft_model(x)
            preds.extend(logits.float().softmax(1).argmax(1).cpu().numpy())
            trues.extend(y.numpy())
    acc = accuracy_score(trues, preds)
    f1 = f1_score(trues, preds, average='macro', zero_division=0)
    print(f'  Epoch {epoch+4}/8 | Acc: {acc*100:.2f}% | F1: {f1*100:.2f}%')

print(classification_report(trues, preds, target_names=CLASS_NAMES, zero_division=0))
torch.save(ft_model.state_dict(), '/content/drive/MyDrive/CAWT_Results/cawt_incart_finetuned.pth')
print('✓ Updated cawt_incart_finetuned.pth')

# ============================================================
#  PER-SAMPLE TRUE vs PREDICTED — INCART (Fine-tuned)
# ============================================================
ft_model.eval()
preds, trues, probs = [], [], []
with torch.no_grad():
    for x, y in test_loader:
        x = x.to(DEVICE)
        with autocast('cuda'): logits = ft_model(x)
        p = logits.float().softmax(1)
        probs.extend(p.cpu().numpy())
        preds.extend(p.argmax(1).cpu().numpy())
        trues.extend(y.numpy())

preds, trues, probs = np.array(preds), np.array(trues), np.array(probs)

print(f'{"="*70}')
print('INCART FINE-TUNED — PER-CLASS BREAKDOWN')
print(f'{"="*70}')
for cls_idx, cls_name in enumerate(CLASS_NAMES):
    mask = trues == cls_idx
    total = mask.sum()
    if total == 0: continue
    correct = (preds[mask] == cls_idx).sum()
    wrong = total - correct
    print(f'\n  {cls_name}: {total} samples | {correct} correct | {wrong} wrong | Acc: {correct/total*100:.2f}%')
    if wrong > 0:
        for pc in np.unique(preds[mask & (preds != trues)]):
            cnt = ((trues == cls_idx) & (preds == pc)).sum()
            print(f'    → misclassified as {CLASS_NAMES[pc]}: {cnt}')

# Sample-level details (first 10 per class)
print(f'\n{"="*70}')
print('SAMPLE-LEVEL DETAILS (first 10 per class)')
print(f'{"="*70}')
for cls_idx, cls_name in enumerate(CLASS_NAMES):
    idxs = np.where(trues == cls_idx)[0][:10]
    if len(idxs) == 0: continue
    print(f'\n  {cls_name}:')
    print(f'  {"Idx":<6} {"True":<22} {"Predicted":<22} {"OK":<4} {"Conf":<6}')
    print(f'  {"-"*62}')
    for i in idxs:
        mark = '✓' if preds[i] == trues[i] else '✗'
        print(f'  {i:<6} {CLASS_NAMES[trues[i]]:<22} {CLASS_NAMES[preds[i]]:<22} {mark:<4} {probs[i][preds[i]]:.4f}')

# Confusion Matrix
cm = confusion_matrix(trues, preds, labels=list(range(5)))
fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASS_NAMES, yticklabels=CLASS_NAMES, ax=ax)
ax.set_title('INCART Fine-Tuned — Confusion Matrix')
ax.set_ylabel('True'); ax.set_xlabel('Predicted')
plt.tight_layout(); plt.show()

# ============================================================
#  t-SNE VISUALIZATION — INCART Fine-Tuned Model
# ============================================================
from sklearn.manifold import TSNE

features, labels = [], []
def hook_fn(module, input, output):
    features.append(input[0].detach().cpu().numpy())

hook = ft_model.head[-1].register_forward_hook(hook_fn)
ft_model.eval()
with torch.no_grad():
    for x, y in test_loader:
        x = x.to(DEVICE)
        with autocast('cuda'): _ = ft_model(x)
        labels.extend(y.numpy())
hook.remove()

all_features = np.concatenate(features, axis=0)
all_labels = np.array(labels)

# Subsample for speed
MAX = 5000
if len(all_features) > MAX:
    idx = np.random.choice(len(all_features), MAX, replace=False)
    feat_sub, label_sub = all_features[idx], all_labels[idx]
else:
    feat_sub, label_sub = all_features, all_labels

print('Running t-SNE (~1-2 min)...')
tsne = TSNE(n_components=2, perplexity=30, n_iter=1000, random_state=42, learning_rate='auto', init='pca')
emb = tsne.fit_transform(feat_sub)

COLORS = ['#2196F3', '#FF9800', '#4CAF50', '#F44336', '#9C27B0']
fig, axes = plt.subplots(1, 2, figsize=(22, 9))

for cls_idx in range(5):
    mask = label_sub == cls_idx
    axes[0].scatter(emb[mask, 0], emb[mask, 1], c=COLORS[cls_idx],
                    label=CLASS_NAMES[cls_idx], s=8, alpha=0.6)
axes[0].legend(fontsize=11, markerscale=3)
axes[0].set_title('t-SNE — INCART Fine-Tuned (All Classes)', fontsize=14)
axes[0].set_xticks([]); axes[0].set_yticks([])

mask_n = label_sub == 0
axes[1].scatter(emb[mask_n, 0], emb[mask_n, 1], c='#E0E0E0', s=6, alpha=0.3, label='Normal')
for cls_idx in [1, 2, 3, 4]:
    mask = label_sub == cls_idx
    axes[1].scatter(emb[mask, 0], emb[mask, 1], c=COLORS[cls_idx],
                    label=CLASS_NAMES[cls_idx], s=20, alpha=0.8, edgecolors='black', linewidths=0.3)
axes[1].legend(fontsize=11, markerscale=2)
axes[1].set_title('t-SNE — Minority Classes Highlighted', fontsize=14)
axes[1].set_xticks([]); axes[1].set_yticks([])

plt.tight_layout(); plt.show()
print('Done!')

# ============================================================
#  TRUE vs PREDICTED COMPARISON — MIT-BIH & INCART
# ============================================================
SHORT = ['N', 'S', 'V', 'F', 'Q']
COLORS_TRUE = ['#2196F3', '#FF9800', '#4CAF50', '#F44336', '#9C27B0']
COLORS_PRED = ['#90CAF9', '#FFE0B2', '#C8E6C9', '#FFCDD2', '#E1BEE7']

fig, axes = plt.subplots(2, 2, figsize=(18, 12))

# --- MIT-BIH ---
mitbih_true = np.bincount(y_true, minlength=5)
mitbih_pred = np.bincount(y_pred, minlength=5)

ax = axes[0, 0]
x = np.arange(5)
w = 0.35
bars1 = ax.bar(x - w/2, mitbih_true, w, label='True', color=COLORS_TRUE, edgecolor='black', linewidth=0.5)
bars2 = ax.bar(x + w/2, mitbih_pred, w, label='Predicted', color=COLORS_PRED, edgecolor='black', linewidth=0.5)
ax.set_xticks(x); ax.set_xticklabels(SHORT, fontsize=12)
ax.set_title('MIT-BIH — True vs Predicted (Counts)', fontsize=14, fontweight='bold')
ax.legend(fontsize=11); ax.set_ylabel('Count')
for b in bars1: ax.text(b.get_x()+b.get_width()/2, b.get_height()+50, f'{int(b.get_height())}', ha='center', fontsize=8)
for b in bars2: ax.text(b.get_x()+b.get_width()/2, b.get_height()+50, f'{int(b.get_height())}', ha='center', fontsize=8)

# MIT-BIH per-class accuracy
ax = axes[0, 1]
mitbih_acc = [(y_pred[y_true == i] == i).mean() * 100 for i in range(5)]
bars = ax.bar(SHORT, mitbih_acc, color=COLORS_TRUE, edgecolor='black', linewidth=0.5)
ax.set_ylim(80, 101); ax.axhline(y=90, color='red', linestyle='--', alpha=0.5, label='90% target')
ax.set_title('MIT-BIH — Per-Class Accuracy', fontsize=14, fontweight='bold')
ax.set_ylabel('Accuracy (%)'); ax.legend()
for b, v in zip(bars, mitbih_acc):
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+0.3, f'{v:.1f}%', ha='center', fontsize=11, fontweight='bold')

# --- INCART ---
incart_true = np.bincount(trues, minlength=5)
incart_pred = np.bincount(preds, minlength=5)

ax = axes[1, 0]
bars1 = ax.bar(x - w/2, incart_true, w, label='True', color=COLORS_TRUE, edgecolor='black', linewidth=0.5)
bars2 = ax.bar(x + w/2, incart_pred, w, label='Predicted', color=COLORS_PRED, edgecolor='black', linewidth=0.5)
ax.set_xticks(x); ax.set_xticklabels(SHORT, fontsize=12)
ax.set_title('INCART (Fine-tuned) — True vs Predicted (Counts)', fontsize=14, fontweight='bold')
ax.legend(fontsize=11); ax.set_ylabel('Count')
for b in bars1: ax.text(b.get_x()+b.get_width()/2, b.get_height()+50, f'{int(b.get_height())}', ha='center', fontsize=8)
for b in bars2: ax.text(b.get_x()+b.get_width()/2, b.get_height()+50, f'{int(b.get_height())}', ha='center', fontsize=8)

# INCART per-class accuracy
ax = axes[1, 1]
incart_acc = [(preds[trues == i] == i).mean() * 100 if (trues == i).sum() > 0 else 0 for i in range(5)]
bars = ax.bar(SHORT, incart_acc, color=COLORS_TRUE, edgecolor='black', linewidth=0.5)
ax.set_ylim(0, 105); ax.axhline(y=90, color='red', linestyle='--', alpha=0.5, label='90% target')
ax.set_title('INCART (Fine-tuned) — Per-Class Accuracy', fontsize=14, fontweight='bold')
ax.set_ylabel('Accuracy (%)'); ax.legend()
for b, v in zip(bars, incart_acc):
    ax.text(b.get_x()+b.get_width()/2, b.get_height()+1, f'{v:.1f}%', ha='center', fontsize=11, fontweight='bold')

plt.suptitle('CAWT Model — True vs Predicted Comparison', fontsize=16, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('/content/drive/MyDrive/CAWT_Results/true_vs_pred_comparison.png', dpi=300, bbox_inches='tight')
plt.show()
print('✓ Saved to CAWT_Results/true_vs_pred_comparison.png')

# ============================================================
#  FULL-SIZE METRIC GRAPHS — MIT-BIH
# ============================================================
from sklearn.metrics import roc_curve, auc, precision_recall_curve, average_precision_score
from sklearn.preprocessing import label_binarize

COLORS = ['#2196F3', '#FF9800', '#4CAF50', '#F44336', '#9C27B0']
SHORT = ['N', 'S', 'V', 'F', 'Q']
y_bin = label_binarize(y_true, classes=range(5))

# 1. LOSS
plt.figure(figsize=(14, 6))
plt.plot(history['train_loss'], label='Train Loss', linewidth=2.5, color='#1976D2')
plt.plot(history['val_loss'], label='Validation Loss', linewidth=2.5, color='#E53935')
plt.title('Training & Validation Loss', fontsize=18, fontweight='bold')
plt.xlabel('Epoch', fontsize=14); plt.ylabel('Loss', fontsize=14)
plt.legend(fontsize=13); plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# 2. ACCURACY
plt.figure(figsize=(14, 6))
plt.plot(history['val_acc'], linewidth=2.5, color='#4CAF50')
plt.axhline(y=0.9, color='red', linestyle='--', linewidth=2, label='90% target')
plt.title('Validation Accuracy', fontsize=18, fontweight='bold')
plt.xlabel('Epoch', fontsize=14); plt.ylabel('Accuracy', fontsize=14)
plt.legend(fontsize=13); plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# 3. MACRO F1
plt.figure(figsize=(14, 6))
plt.plot(history['val_f1'], linewidth=2.5, color='#FF9800')
plt.axhline(y=0.9, color='red', linestyle='--', linewidth=2, label='90% target')
plt.title('Validation Macro F1', fontsize=18, fontweight='bold')
plt.xlabel('Epoch', fontsize=14); plt.ylabel('F1 Score', fontsize=14)
plt.legend(fontsize=13); plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# 4. PER-CLASS F1 BAR
plt.figure(figsize=(12, 7))
from sklearn.metrics import f1_score as f1s
per_f1 = [f1s(y_true == i, y_pred == i) for i in range(5)]
bars = plt.bar(CLASS_NAMES, per_f1, color=COLORS, edgecolor='black', linewidth=1, width=0.6)
plt.axhline(y=0.9, color='red', linestyle='--', linewidth=2, label='90% target')
plt.ylim(0.7, 1.03)
plt.title('Per-Class F1 Score', fontsize=18, fontweight='bold')
plt.ylabel('F1 Score', fontsize=14); plt.legend(fontsize=13)
for b, v in zip(bars, per_f1):
    plt.text(b.get_x()+b.get_width()/2, b.get_height()+0.008, f'{v:.3f}', ha='center', fontsize=14, fontweight='bold')
plt.tight_layout(); plt.show()

# 5. SENSITIVITY vs SPECIFICITY
plt.figure(figsize=(12, 7))
cm = confusion_matrix(y_true, y_pred, labels=list(range(5)))
sens, spec = [], []
for i in range(5):
    tp=cm[i,i]; fn=cm[i,:].sum()-tp; fp=cm[:,i].sum()-tp; tn=cm.sum()-tp-fp-fn
    sens.append(tp/(tp+fn+1e-9)); spec.append(tn/(tn+fp+1e-9))
x = np.arange(5); w = 0.35
plt.bar(x-w/2, sens, w, label='Sensitivity', color=COLORS, edgecolor='black')
plt.bar(x+w/2, spec, w, label='Specificity', color=['#90CAF9','#FFE0B2','#C8E6C9','#FFCDD2','#E1BEE7'], edgecolor='black')
plt.xticks(x, CLASS_NAMES, fontsize=11); plt.ylim(0.8, 1.02)
plt.title('Sensitivity vs Specificity', fontsize=18, fontweight='bold')
plt.ylabel('Score', fontsize=14); plt.legend(fontsize=13)
plt.tight_layout(); plt.show()

# 6. ROC CURVES
plt.figure(figsize=(12, 10))
for i in range(5):
    fpr, tpr, _ = roc_curve(y_bin[:, i], y_probs[:, i])
    plt.plot(fpr, tpr, color=COLORS[i], lw=3, label=f'{CLASS_NAMES[i]} (AUC={auc(fpr, tpr):.4f})')
plt.plot([0,1],[0,1],'k--',lw=1.5)
plt.title('ROC Curves (One-vs-Rest)', fontsize=18, fontweight='bold')
plt.xlabel('False Positive Rate', fontsize=14); plt.ylabel('True Positive Rate', fontsize=14)
plt.legend(fontsize=12); plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# 7. PRECISION-RECALL CURVES
plt.figure(figsize=(12, 10))
for i in range(5):
    p, r, _ = precision_recall_curve(y_bin[:, i], y_probs[:, i])
    ap = average_precision_score(y_bin[:, i], y_probs[:, i])
    plt.plot(r, p, color=COLORS[i], lw=3, label=f'{CLASS_NAMES[i]} (AP={ap:.4f})')
plt.title('Precision-Recall Curves', fontsize=18, fontweight='bold')
plt.xlabel('Recall', fontsize=14); plt.ylabel('Precision', fontsize=14)
plt.legend(fontsize=12); plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

# 8. CONFUSION MATRIX (large)
fig, axes = plt.subplots(1, 2, figsize=(22, 9))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASS_NAMES,
            yticklabels=CLASS_NAMES, ax=axes[0], annot_kws={'size': 14})
axes[0].set_title('Confusion Matrix (Counts)', fontsize=16, fontweight='bold')
axes[0].set_ylabel('True', fontsize=13); axes[0].set_xlabel('Predicted', fontsize=13)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
sns.heatmap(cm_norm, annot=True, fmt='.3f', cmap='Greens', xticklabels=CLASS_NAMES,
            yticklabels=CLASS_NAMES, ax=axes[1], annot_kws={'size': 14})
axes[1].set_title('Normalized Confusion Matrix', fontsize=16, fontweight='bold')
axes[1].set_ylabel('True', fontsize=13); axes[1].set_xlabel('Predicted', fontsize=13)
plt.tight_layout(); plt.show()

print('✓ All 8 graphs displayed!')

# ============================================================
#  SAVE EVERYTHING TO DRIVE (before disconnect!)
# ============================================================
import shutil

SAVE_DIR = '/content/drive/MyDrive/CAWT_Results'
os.makedirs(SAVE_DIR, exist_ok=True)

# 1. Model weights
shutil.copy('cawt_best.pth', f'{SAVE_DIR}/cawt_best.pth')
print('✓ cawt_best.pth')

# 2. Training history
import json
with open(f'{SAVE_DIR}/training_history.json', 'w') as f:
    json.dump(history, f)
print('✓ training_history.json')

# 3. Save all current plots
for name, data in [('y_true', y_true), ('y_pred', y_pred), ('y_probs', y_probs)]:
    np.save(f'{SAVE_DIR}/{name}.npy', data)
print('✓ y_true.npy, y_pred.npy, y_probs.npy')

# 4. Save the notebook itself
shutil.copy('/content/CAWT_Final.ipynb', f'{SAVE_DIR}/CAWT_Final_backup.ipynb') if os.path.exists('/content/CAWT_Final.ipynb') else None

# 5. Config
with open(f'{SAVE_DIR}/config.json', 'w') as f:
    cfg_save = {k: str(v) if k == 'device' else v for k, v in CONFIG.items()}
    json.dump(cfg_save, f, indent=2)
print('✓ config.json')

print(f'\n{"="*50}')
print(f'ALL SAVED TO: {SAVE_DIR}')
print(f'{"="*50}')
print('Files:')
for f in sorted(os.listdir(SAVE_DIR)):
    size = os.path.getsize(f'{SAVE_DIR}/{f}') / 1024
    print(f'  {f} ({size:.1f} KB)')

# INCART results + validation data
np.save(f'{SAVE_DIR}/X_val.npy', X_val)
np.save(f'{SAVE_DIR}/y_val.npy', y_val)
print('✓ X_val.npy, y_val.npy (so you can regenerate graphs without re-extracting)')

# INCART fine-tuned predictions
np.save(f'{SAVE_DIR}/incart_trues.npy', trues)
np.save(f'{SAVE_DIR}/incart_preds.npy', preds)
np.save(f'{SAVE_DIR}/incart_probs.npy', probs)
print('✓ INCART predictions saved')

# Classification reports as text
with open(f'{SAVE_DIR}/results_summary.txt', 'w') as f:
    f.write('MIT-BIH RESULTS\n' + '='*50 + '\n')
    f.write(classification_report(y_true, y_pred, target_names=CLASS_NAMES, zero_division=0))
    f.write(f'\nAccuracy: {accuracy_score(y_true, y_pred)*100:.2f}%\n')
    f.write(f'\n\nINCART FINE-TUNED RESULTS\n' + '='*50 + '\n')
    f.write(classification_report(trues, preds, target_names=CLASS_NAMES, zero_division=0))
    f.write(f'\nAccuracy: {accuracy_score(trues, preds)*100:.2f}%\n')
print('✓ results_summary.txt')

print('\n✅ Everything saved! Safe to disconnect now.')

# ============================================================
#  ADDITIONAL PAPER GRAPHS
# ============================================================

# 1. CLASS DISTRIBUTION (Before vs After SMOTE)
fig, axes = plt.subplots(1, 2, figsize=(18, 7))
orig_counts = np.bincount(y_all, minlength=5)
smote_counts = np.array([72484]*5)  # From your SMOTE output

axes[0].bar(CLASS_NAMES, orig_counts, color=COLORS, edgecolor='black')
axes[0].set_title('Original Distribution', fontsize=16, fontweight='bold')
axes[0].set_ylabel('Count', fontsize=13)
for i, v in enumerate(orig_counts):
    axes[0].text(i, v+500, f'{v:,}', ha='center', fontsize=11, fontweight='bold')

axes[1].bar(CLASS_NAMES, smote_counts, color=COLORS, edgecolor='black')
axes[1].set_title('After SMOTE Balancing', fontsize=16, fontweight='bold')
axes[1].set_ylabel('Count', fontsize=13)
for i, v in enumerate(smote_counts):
    axes[1].text(i, v+500, f'{v:,}', ha='center', fontsize=11, fontweight='bold')
plt.suptitle('Class Distribution — Before vs After SMOTE', fontsize=18, fontweight='bold')
plt.tight_layout(); plt.show()

# 2. SAMPLE ECG BEATS PER CLASS (1 row per class)
fig, axes = plt.subplots(5, 5, figsize=(24, 15))
fig.suptitle('Sample ECG Beats Per Class (Validation Set)', fontsize=18, fontweight='bold')
for cls_idx in range(5):
    idxs = np.where(y_true == cls_idx)[0][:5]
    for j, idx in enumerate(idxs):
        ax = axes[cls_idx, j]
        ax.plot(X_val[idx], color=COLORS[cls_idx], linewidth=1.5)
        ax.set_ylim(-0.1, 1.1)
        if j == 0: ax.set_ylabel(CLASS_NAMES[cls_idx], fontsize=10, fontweight='bold')
        if cls_idx == 0: ax.set_title(f'Sample {j+1}', fontsize=11)
        ax.set_xticks([]); ax.set_yticks([])
plt.tight_layout(); plt.show()

# 3. LEARNING RATE SCHEDULE
plt.figure(figsize=(14, 5))
epochs = np.arange(1, len(history['train_loss'])+1)
# Reconstruct OneCycleLR schedule
total_steps = len(history['train_loss']) * 708  # epochs * batches
lr_schedule = []
for e in range(len(history['train_loss'])):
    pct = e / len(history['train_loss'])
    if pct < 0.3:
        lr = 3e-4 * pct / 0.3
    else:
        lr = 3e-4 * 0.5 * (1 + np.cos(np.pi * (pct - 0.3) / 0.7))
    lr_schedule.append(lr)
plt.plot(epochs, lr_schedule, linewidth=2.5, color='#E53935')
plt.title('OneCycleLR Schedule', fontsize=18, fontweight='bold')
plt.xlabel('Epoch', fontsize=14); plt.ylabel('Learning Rate', fontsize=14)
plt.grid(alpha=0.3); plt.tight_layout(); plt.show()

print('✓ All 3 additional graphs done!')

# Save both models to Drive
import shutil
shutil.copy('cawt_best.pth', '/content/drive/MyDrive/CAWT_Results/cawt_best.pth')
print('✓ cawt_best.pth saved to Drive')
print(f'  Size: {os.path.getsize("cawt_best.pth")/1e6:.1f} MB')